## Decision Tree

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("company_salary.csv")
df

       Company                  Job     Degree  Salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [3]:
inputs = df.drop('Salary_more_then_100k',axis=1)
target = df['Salary_more_then_100k']

In [4]:
inputs

       Company                  Job     Degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [5]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: Salary_more_then_100k, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_Company = LabelEncoder()
le_Job = LabelEncoder()
le_Degree = LabelEncoder()

Creating extra column in inputs

In [28]:
inputs['Company_n'] = le_Company.fit_transform(inputs['Company'])
inputs['Job_n'] = le_Job.fit_transform(inputs['Job'])
inputs['Degree_n'] = le_Degree.fit_transform(inputs['Degree'])

In [29]:
inputs

       Company                  Job     Degree  Company_n  Job_n  Degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [10]:
inputs_n = inputs.drop(['Company','Job','Degree'],axis=1)

In [11]:
inputs_n

    Company_n  Job_n  Degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [12]:
from sklearn import tree
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(inputs_n, target, test_size=0.4, random_state=42)

In [14]:
x_train

    Company_n  Job_n  Degree_n
9           0      0         1
2           2      0         0
15          1      1         1
4           2      1         0
7           0      1         0
10          1      2         0
12          1      0         0
3           2      0         1
6           0      2         1

In [15]:
x_test

    Company_n  Job_n  Degree_n
0           2      2         0
1           2      2         1
5           2      1         1
14          1      1         0
13          1      0         1
11          1      2         1
8           0      0         0

In [16]:
y_test

0     0
1     0
5     1
14    1
13    1
11    1
8     0
Name: Salary_more_then_100k, dtype: int64

In [17]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: Salary_more_then_100k, dtype: int64

In [18]:
model = tree.DecisionTreeClassifier()

In [25]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [19]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

The Score will be one becuase all the datamis trained and same is tested so it will be correct always.

In [20]:
model.predict(x_test)

array([0, 0, 0, 1, 1, 1, 1])

In [21]:
model.score(x_test,y_test)

0.7142857142857143

In [22]:
model.predict([[2,0,0]])

C:\Users\Soham\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [26]:
model.score(inputs_n,target)

1.0

In [27]:
model.predict(inputs_n)

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1])