# Introduction to Pandas

## What is Pandas?
Pandas is the most popular Python Data Analysis Library, used for manipulating, cleaning, and analyzing structured data.

## Why use Pandas?
Loads data fast: Reads CSV, Excel, and SQL files in a single line.
Uses vectorized math to process millions of rows instantly.
Drops or fills missing values and removes duplicates easily.

In [ ]:
print("Introduction to Pandas")

In [ ]:
!conda config --add channels defaults
!conda config --add channels conda-forge

In [ ]:
!conda install pandas

# Key Data Structures in Pandas
*Series
*DataFrame

In [3]:
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

In [ ]:
s

In [ ]:
df = pd.DataFrame({"names": ["Soham", "Kajal", "Kayy", "Spartan"], "marks": [94, 98, 97, 95]})

In [ ]:
df

In [40]:
df = pd.read_csv("Book2.csv")

In [41]:
df

       Name  Marks
0      Kayy     96
1     Soham     95
2   Spartan     89
3    Kajall     90
4     Danny     94
5      Anvi     94
6     Saily     93
7  Himanshu     93
8       NaN     92

In [27]:
df.head()

      Name  Marks
0     Kayy   96.0
1    Soham    NaN
2  Spartan   89.0
3   Kajall   90.0
4    Danny    NaN

In [28]:
df.tail()

       Name  Marks
4     Danny    NaN
5      Anvi   94.0
6     Saily   93.0
7  Himanshu   93.0
8       NaN   92.0

In [8]:
df.describe()

           Marks
count   9.000000
mean   92.888889
std     2.260777
min    89.000000
25%    92.000000
50%    93.000000
75%    94.000000
max    96.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str
 1   Marks   9 non-null      int64
dtypes: int64(1), str(1)
memory usage: 276.0 bytes

## Data Selection

In [13]:
df["Name"]

0        Kayy
1       Soham
2     Spartan
3      Kajall
4       Danny
5        Anvi
6       Saily
7    Himanshu
8        Jnvi
Name: Name, dtype: str

In [14]:
df["Marks"]

0    96
1    95
2    89
3    90
4    94
5    94
6    93
7    93
8    92
Name: Marks, dtype: int64

In [15]:
type(df["Name"])

pandas.Series

In [19]:
df[["Name", "Marks"]]

       Name  Marks
0      Kayy     96
1     Soham     95
2   Spartan     89
3    Kajall     90
4     Danny     94
5      Anvi     94
6     Saily     93
7  Himanshu     93
8      Jnvi     92

In [23]:
df.iloc[0]

Name     Kayy
Marks      96
Name: 0, dtype: object

In [29]:
df.dropna()

       Name  Marks
0      Kayy   96.0
2   Spartan   89.0
3    Kajall   90.0
5      Anvi   94.0
6     Saily   93.0
7  Himanshu   93.0

In [33]:
df.fillna(7)

       Name  Marks
0      Kayy   96.0
1     Soham    7.0
2   Spartan   89.0
3    Kajall   90.0
4     Danny    7.0
5      Anvi   94.0
6     Saily   93.0
7  Himanshu   93.0
8         7   92.0

In [35]:
df.rename(columns={"Name": "Friends"})

    Friends  Marks
0      Kayy   96.0
1     Soham    NaN
2   Spartan   89.0
3    Kajall   90.0
4     Danny    NaN
5      Anvi   94.0
6     Saily   93.0
7  Himanshu   93.0
8       NaN   92.0

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      str
 1   Marks   7 non-null      float64
dtypes: float64(1), str(1)
memory usage: 276.0 bytes

In [59]:
df['Marks'] = df['Marks'].astype(int)

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      str
 1   Marks       9 non-null      int64
 2   zeroes      9 non-null      int64
 3   zeroes + 1  9 non-null      int64
dtypes: int64(3), str(1)
memory usage: 420.0 bytes

In [61]:
df

       Name  Marks  zeroes  zeroes + 1
0      Kayy     96       0           1
1     Soham     95       0           1
2   Spartan     89       0           1
3    Kajall     90       0           1
4     Danny     94       0           1
5      Anvi     94       0           1
6     Saily     93       0           1
7  Himanshu     93       0           1
8       NaN     92       0           1

In [62]:
df["Marks"][0]

np.int64(96)

In [63]:
len(df)

9

In [64]:
df["zeroes"] = [0 for i in range(len(df))]

In [65]:
df

       Name  Marks  zeroes  zeroes + 1
0      Kayy     96       0           1
1     Soham     95       0           1
2   Spartan     89       0           1
3    Kajall     90       0           1
4     Danny     94       0           1
5      Anvi     94       0           1
6     Saily     93       0           1
7  Himanshu     93       0           1
8       NaN     92       0           1

In [66]:
def fx(a):
    return a*a
df["zeroes + 1"] = df["Marks"] .apply(fx)

In [74]:
df

       Name  Marks  zeroes  zeroes + 1
0      Kayy     96       0        9216
1     Soham     95       0        9025
2   Spartan     89       0        7921
3    Kajall     90       0        8100
4     Danny     94       0        8836
5      Anvi     94       0        8836
6     Saily     93       0        8649
7  Himanshu     93       0        8649
8       NaN     92       0        8464

In [78]:
df.to_csv("data/export.csv", index=False)

In [10]:
df1 = pd.DataFrame({
    "name": ["Ronaldo", "Messi", "Neymar", "Bale", "Lewy", "Chhetri"],
    "Marks": [900,800,500,300,567,634],
})

In [11]:
df1

      name  Marks
0  Ronaldo    900
1    Messi    800
2   Neymar    500
3     Bale    300
4     Lewy    567
5  Chhetri    634

In [18]:
df2 = pd.DataFrame({
    "name": ["Buffon", "Cassilas", "Schiemichel", "Nuer", "Cortuios", "De Gea"],
    "Marks": [210, 209, 190, 215, 159, 147],
})

In [19]:
df2

          name  Marks
0       Buffon    210
1     Cassilas    209
2  Schiemichel    190
3         Nuer    215
4     Cortuios    159
5       De Gea    147

In [20]:
pd.concat([df1, df2])

          name  Marks
0      Ronaldo    900
1        Messi    800
2       Neymar    500
3         Bale    300
4         Lewy    567
5      Chhetri    634
0       Buffon    210
1     Cassilas    209
2  Schiemichel    190
3         Nuer    215
4     Cortuios    159
5       De Gea    147

In [26]:
df1 = pd.DataFrame({"name": ["Ronamdo", "Messi"], "Marks": [900,800]})

In [27]:
df1

      name  Marks
0  Ronamdo    900
1    Messi    800

In [31]:
df2 = pd.DataFrame({"name": ["Ronamdo", "Messi",  "Neymsr"], "Roll no.": [1,2,3]})

In [32]:
df2

      name  Roll no.
0  Ronamdo         1
1    Messi         2
2   Neymsr         3

In [33]:
pd.merge(df1, df2, on="name")

      name  Marks  Roll no.
0  Ronamdo    900         1
1    Messi    800         2